a = int(input())
b = int(input())
c = int(input())
a1 = int(input())
b1 = int(input())
c1 = int(input())
A = (a // a1) * (b // b1) * (c // c1)
B = (b // a1) * (a // b1) * (c // c1)
C = (c // a1) * (b // b1) * (a // c1)
D = (a // a1) * (c // b1) * (b // c1)
E = (b // a1) * (c // b1) * (a // c1)
F = (c // a1) * (a // b1) * (b // c1)
x = max(A, B, C, D, E, F)
print(x)
